version: "3.8"

services:
  mariadb:
    image: mariadb
    restart: always
    expose:
      - "3306"
    ports:
      - "6033:3306"
    environment:
      - MARIADB_DATABASE=auction
      - MARIADB_ROOT_PASSWORD=mariadb
      - MARIADB_INITDB_SKIP_TZINFO=1

  app:
    depends_on:
      - mariadb
    image: shafiq98/auction-service:4
    restart: always
    expose:
      - "8081"
    ports:
      - "8081:8081"
    volumes:
      - ./src/main/resources:/var/lib/spring
